# Generated by Django 5.2.2 on 2025-06-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productfeatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_type',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='weight',
        ),
    ]
