# Generated by Django 5.2.2 on 2025-06-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_type_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
