# Generated by Django 5.2.2 on 2025-06-13 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product'),
        ),
    ]
