# Generated by Django 5.2.2 on 2025-06-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_temporder_temporderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
