# Generated by Django 5.2.1 on 2025-06-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_alt_txt_remove_user_auto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tenant_id',
        ),
    ]
