# Generated by Django 5.2.3 on 2025-06-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auto_id',
            field=models.PositiveIntegerField(db_index=True, null=True, unique=True),
        ),
    ]
