# Generated by Django 5.2.1 on 2025-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'printfun',
                'verbose_name_plural': 'printfuns',
                'db_table': 'app_name_printfun',
            },
        ),
    ]
