# Generated by Django 5.2.1 on 2025-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printclass',
            options={},
        ),
        migrations.AddField(
            model_name='printclass',
            name='email',
            field=models.EmailField(default=1, max_length=59),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='printclass',
            table=None,
        ),
    ]
