# Generated by Django 5.2.1 on 2025-05-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_alter_printclass_options_printclass_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Next_pageClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=59)),
            ],
        ),
    ]
