# Generated by Django 5.2.1 on 2025-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0003_next_pageclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Next_pageClass',
        ),
    ]
