# Generated by Django 5.2.1 on 2025-05-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0004_pingclass_delete_next_pageclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pingclass',
            options={'verbose_name': 'ping', 'verbose_name_plural': 'ping'},
        ),
        migrations.AlterModelTable(
            name='pingclass',
            table='app_name_ping',
        ),
    ]
