# Generated by Django 5.2.1 on 2025-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0005_alter_pingclass_options_alter_pingclass_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='PingClass',
        ),
    ]
