# Generated by Django 5.2.1 on 2025-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0013_cvlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
    ]
