# Generated by Django 5.2.1 on 2025-05-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0014_kvlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KvLog',
        ),
    ]
